apiVersion: v1
kind: Pod
metadata:
  name: "pychyderm-exporter"
  annotations:
    prometheus.io/port: '9426'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  containers:
    - image: jacoschalijmd/pychyderm-exporter:latest
      imagePullPolicy: Always
      name: "pychyderm-exporter"
      resources:
        limits:
          memory: "1Gi"
          cpu: 1
        requests:
          memory: "1Gi"
          cpu: 1
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
